### ISSUE TITLE
Could not find program tesseract

### ISSUE THREAD

**Issue by billydekid** [keensoft/alfresco-simple-ocr#18]
Hi,

I just got unstable conditions when this addon failed to process. I ran the Extract OCR on folder's rule, when content enter that folder.

See the parts of log below:

```
err:        Fatal error: exception Failure("Could not find program tesseract. Make sure this program exists and can be found in your search path.
Use command line options to specify a custom binary.")

        at es.keensoft.alfresco.ocr.OCRExtractAction.executeImpl(OCRExtractAction.java:143)
        at org.alfresco.repo.action.executer.ActionExecuterAbstractBase.execute(ActionExecuterAbstractBase.java:267)
        at org.alfresco.repo.action.ActionServiceImpl.directActionExecution(ActionServiceImpl.java:839)
        at org.alfresco.repo.action.executer.CompositeActionExecuter.executeImpl(CompositeActionExecuter.java:66)
        at org.alfresco.repo.action.executer.ActionExecuterAbstractBase.execute(ActionExecuterAbstractBase.java:267)
        at org.alfresco.repo.action.ActionServiceImpl.directActionExecution(ActionServiceImpl.java:839)
        at org.alfresco.repo.action.ActionServiceImpl.executeActionImpl(ActionServiceImpl.java:740)
        at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper$1$1.execute(AsynchronousActionExecutionQueueImpl.java:423)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:326)
        at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper$1.doWork(AsynchronousActionExecutionQueueImpl.java:432)
        at org.alfresco.repo.tenant.TenantUtil.runAsWork(TenantUtil.java:119)
        at org.alfresco.repo.tenant.TenantUtil.runAsTenant(TenantUtil.java:88)
        at org.alfresco.repo.tenant.TenantUtil$1.doWork(TenantUtil.java:62)
        at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
        at org.alfresco.repo.tenant.TenantUtil.runAsUserTenant(TenantUtil.java:58)
        at org.alfresco.repo.action.AsynchronousActionExecutionQueueImpl$ActionExecutionWrapper.run(AsynchronousActionExecutionQueueImpl.java:435)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.alfresco.service.cmr.repository.ContentIOException: 09100114 Failed to perform OCR transformation:
Execution result:
   os:         Linux
   command:    /usr/local/bin/pdfsandwich -verbose -lang eng+ind -rgb /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_6093412488594768960.pdf -o /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_6093412488594768960_ocr.pdf
   succeeded:  false
   exit code:  2
   out:
   err:        Fatal error: exception Failure("Could not find program tesseract. Make sure this program exists and can be found in your search path.
Use command line options to specify a custom binary.")
```

I can run tesseract normally from command line:

```
root@dmsdev:/opt/alfresco-community# tesseract -v
tesseract 3.05.00dev
 leptonica-1.73
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8
```

When I tried to run it manually from the shell, it works:

```
root@dmsdev:/opt/alfresco-community/tomcat/shared/classes# /usr/local/bin/pdfsandwich -verbose -lang eng+ind -rgb /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1877691809857980597.pdf -o /opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1877691809857980597_ocr.pdf
...<skip>
OCR done. Writing "/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1877691809857980597_ocr.pdf"
pdfunite /tmp/pdfsandwich3c120a.pdf /tmp/pdfsandwich3601ee.pdf /tmp/pdfsandwich_outputafffcf.pdf

/opt/alfresco-community/tomcat/temp/Alfresco/OCRTransformWorker_source_1877691809857980597_ocr.pdf generated.

Done.
```

The problem is gone when I restart the Alfresco. What's the problem?

Thanks,
[bayu]

**Comment by angelborroy-ks** [comment]
Please, try to apply any of this alternatives: https://github.com/keensoft/alfresco-simple-ocr/wiki/FAQ

**Comment by billydekid** [comment]
OK, I will apply it and waiting for some times. Thank you.

---
wassalam,
[bayu]

/sent from Android phone/
