### ISSUE TITLE
Error setting versionService after the "Action is not asynchronous by design anymore" changes

### ISSUE THREAD

**Issue by douglascrp** [keensoft/alfresco-simple-ocr#2]
I've updated my source code, compiled it and tried in the same server I was testing before, and now, when the server starts, I see the error message bellow and Alfresco doesn't work after that:
```

Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'versionService' of bean class [es.keensoft.alfresco.ocr.OCRExtractAction]: Bean property 'versionService' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:1044)
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:904)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:57)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1452)
```

**Comment by angelborroy-ks** [comment]
Try to uninstall the addon and to install the new one, maybe that snapshot version is not overriding the previous one.

**Comment by douglascrp** [comment]
Sorry, my mistake.
I forgot to remove the old amp and ended up installing both.
Once I removed the old one, everything worked.
