### ISSUE TITLE
Async error

### ISSUE THREAD

**Issue by lelive** [keensoft/alfresco-simple-ocr#38]
Hello,
my installation work fine with your plugin when i put pdf files with drag & drop. 
But when i click on "OCR" button in share, alfresco send a popup say "some error happened..." and catalina.out say :
Caused by: org.alfresco.error.AlfrescoRuntimeException: 08070071 Invalid parameter asynchronous for action/condition ocr-extract at org.alfresco.repo.web.scripts.rule.AbstractRuleWebScript.parseJsonParameterValues(AbstractRuleWebScript.java:363)
	at org.alfresco.repo.web.scripts.rule.AbstractRuleWebScript.parseJsonAction(AbstractRuleWebScript.java:255)
	at org.alfresco.repo.web.scripts.rule.ActionQueuePost.executeImpl(ActionQueuePost.java:75)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)

Can you help me ?

Olivier

**Comment by angelborroy-ks** [comment]
It looks like you have different releases for repo & share part. Are you using last 2.3.1 version in both `simple-ocr-repo.jar` & `simple-ocr-share.jar` artefacts?

**Comment by lelive** [comment]
Yes, please see below
Module 'org.alfresco.integrations.google.docs' installed in 'tomcat/webapps/alfresco'
   -    Title:        Alfresco / Google Docs Integration
   -    Version:      3.0.3
   -    Install Date: Fri Sep 01 12:13:51 CEST 2017
   -    Description:   The Repository side artifacts of the Alfresco / Google Docs Integration.
Module 'simple-ocr-repo' installed in 'tomcat/webapps/alfresco'
   -    Title:        simple-ocr-repo Repository AMP project
   -    Version:      1.1.1.1609250928
   -    Install Date: Thu Sep 07 12:43:11 CEST 2017
   -    Description:   Manages the lifecycle of the simple-ocr-repo Repository AMP (Alfresco Module Package)
Module 'alfresco-share-services' installed in 'tomcat/webapps/alfresco'
   -    Title:        Alfresco Share Services AMP
   -    Version:      5.2.0
   -    Install Date: Fri Sep 01 12:13:54 CEST 2017
   -    Description:   Module to be applied to alfresco.war, containing APIs for Alfresco Share
Module 'alfresco-aos-module' installed in 'tomcat/webapps/alfresco'
   -    Title:        Alfresco Office Services Module
   -    Version:      1.1.5
   -    Install Date: Fri Sep 01 12:13:53 CEST 2017
   -    Description:   Allows applications that can talk to a SharePoint server to talk to your Alfresco installation

-rw-r--r-- 1 root root 27776 sept.  7 12:12 simple-ocr-repo-2.3.1.jar
-rw-r--r-- 1 root root 12213 sept.  7 12:12 simple-ocr-share-2.3.1.jar

But in catalina.out i found this :
2017-09-07 18:28:37,023  INFO  [repo.module.ModuleServiceImpl] [localhost-startStop-1] Starting module 'simple-ocr-repo' version 1.1.1.1609250928.
simple-ocr-repo Platform Jar Module - SDK 3, 2.3.1, Platform JAR Module (to be included in the alfresco.war) - SDK 3
simple-ocr-share Share Jar Module - SDK 3, 2.3.1, Share JAR Module (to be included in the share.war) - SDK 3
 2017-09-07 18:31:37,578  WARN  [repo.module.ModuleServiceImpl] [localhost-startStop-1] A previously-installed module 'simple-ocr-repo' (version 1.1.1.1609250928) is not present in your distribution.

What does it mean ? What should i do ?

Thank for your reply !

**Comment by angelborroy-ks** [comment]
It looks like upgrading from version 1.1.1 is not working successfully. Probably due to the change of packaging from AMP to JAR. To solve this, download original **alfresco.war** from page https://community.alfresco.com/docs/DOC-7050-alfresco-community-edition-201707-ga-file-list 

You'll find it inside **alfresco-community-distribution-201707.zip** download. After replacing this file in your `alfresco/tomcat/webapps` folder, run `apply_amps.sh` again an re-start.

**Comment by lelive** [comment]
Ok, will do that tomorrow and return the result.

Olivier

**Comment by lelive** [comment]
Hello,
i'am sorry but same issue :
Installing AMP '/root/simple-ocr-repo.amp' into WAR 'tomcat/webapps/alfresco.war'
Backing up file...
The back up is at '/opt/alfresco/tomcat/webapps/alfresco.war-1505114735268.bak'
INFO: Checking the war version using /WEB-INF/classes/alfresco/version.properties
Adding files relating to version '1.1.1.1609250928' of module 'simple-ocr-repo'
   - File '/WEB-INF/lib/simple-ocr-repo.jar' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/bootstrap-context.xml' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/model-context.xml' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context/service-context.xml' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/simple-ocr-repo/context' added to war
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo_de.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo_es.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo_it.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages/simple-ocr-repo_pt.properties' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/simple-ocr-repo/messages' added to war
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/model/ocr-model.xml' added to war from amp
   - Directory '/WEB-INF/classes/alfresco/module/simple-ocr-repo/model' added to war
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/alfresco-global.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/log4j.properties' added to war from amp
   - File '/WEB-INF/classes/alfresco/module/simple-ocr-repo/module-context.xml' added to war from amp
root@alfTRANSDEV:/opt/alfresco# java/bin/java -jar ./bin/alfresco-mmt.jar list tomcat/webapps/alfresco.war
Module 'simple-ocr-repo' installed in 'tomcat/webapps/alfresco.war'
   -    Title:        simple-ocr-repo Repository AMP project
   -    Version:      1.1.1.1609250928
   -    Install Date: Mon Sep 11 09:25:35 CEST 2017
   -    Description:   Manages the lifecycle of the simple-ocr-repo Repository AMP (Alfresco Module Package)
--------------------------
2017-09-11 09:28:09,228  INFO  [web.site.EditionInterceptor] [http-apr-8080-exec-1] Successfully retrieved license information from Alfresco.
 2017-09-11 09:28:49,674  INFO  [web.scripts.DictionaryQuery] [http-apr-8080-exec-5] Successfully retrieved Data Dictionary from Alfresco.
 2017-09-11 09:29:07,152  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-1] Exception from executeScript: 08110001 Wrapped Exception (with status template): 08110020 Invalid parameter asynchronous for action/condition ocr-extract
 org.springframework.extensions.webscripts.WebScriptException: 08110001 Wrapped Exception (with status template): 08110020 Invalid parameter asynchronous for action/condition ocr-extract
[...]
Caused by: org.alfresco.error.AlfrescoRuntimeException: 08110020 Invalid parameter asynchronous for action/condition ocr-extract
	at org.alfresco.repo.web.scripts.rule.AbstractRuleWebScript.parseJsonParameterValues(AbstractRuleWebScript.java:363)
	at org.alfresco.repo.web.scripts.rule.AbstractRuleWebScript.parseJsonAction(AbstractRuleWebScript.java:255)
	at org.alfresco.repo.web.scripts.rule.ActionQueuePost.executeImpl(ActionQueuePost.java:75)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
	... 37 more

In catalina.out, a found this line : 
[repo.module.ModuleServiceImpl] [localhost-startStop-1] A previously-installed module 'simple-ocr-repo' (version 1.1.1.1609250928) is not present in your distribution

I put the files .jar in alfresco/modules, is it right ?

**Comment by angelborroy-ks** [comment]
Did you remove `simple-ocr-repo.amp` file from `alfresco\amps`? It looks like you are trying to install version 1.x (provided by AMP) and version 2.X (provided by JAR).

If you use JAR file from version 2.X, you just need to copy this files to `modules` directories and it's done.

**Comment by lelive** [comment]
No file simple-ocr-repo.amp in amps directory : 
/opt/alfresco# ls amps
alfresco-aos-module-1.1.5.amp  alfresco-googledocs-repo-3.0.3.amp  alfresco-share-services.amp

ls modules/share/
simple-ocr-repo-2.3.1.jar  simple-ocr-share-2.3.1.jar

I uninstalled amp plugin : 
root@xxx:/opt/alfresco# java/bin/java -jar ./bin/alfresco-mmt.jar list tomcat/webapps/share.war
Module 'org.alfresco.integrations.share.google.docs' installed in 'tomcat/webapps/share.war'
   -    Title:        Alfresco / Google Docs Share Module
   -    Version:      3.0.3
   -    Install Date: Fri Sep 01 12:13:57 CEST 2017
   -    Description:   The Share side artifacts of the Alfresco / Google Docs Integration.
root@xxx:/opt/alfresco# java/bin/java -jar ./bin/alfresco-mmt.jar list tomcat/webapps/alfresco.war
No modules are installed in this WAR file

But same issue

2017-09-11 10:56:32,793  INFO  [web.site.EditionInterceptor] [http-apr-8080-exec-1] Successfully retrieved license information from Alfresco.
 2017-09-11 10:57:15,783  INFO  [web.scripts.DictionaryQuery] [http-apr-8080-exec-5] Successfully retrieved Data Dictionary from Alfresco.
 2017-09-11 10:57:27,003  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-5] Exception from executeScript: 08110001 Wrapped Exception (with status template): 08110046 Invalid parameter asynchronous for action/condition ocr-extract
 org.springframework.extensions.webscripts.WebScriptException: 08110001 Wrapped Exception (with status template): 08110046 Invalid parameter asynchronous for action/condition ocr-extract
[...]
Caused by: org.alfresco.error.AlfrescoRuntimeException: 08110046 Invalid parameter asynchronous for action/condition ocr-extract
	at org.alfresco.repo.web.scripts.rule.AbstractRuleWebScript.parseJsonParameterValues(AbstractRuleWebScript.java:363)
	at org.alfresco.repo.web.scripts.rule.AbstractRuleWebScript.parseJsonAction(AbstractRuleWebScript.java:255)
	at org.alfresco.repo.web.scripts.rule.ActionQueuePost.executeImpl(ActionQueuePost.java:75)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
	... 36 more

**Comment by angelborroy-ks** [comment]
You need to use original `alfresco.war` file from distribution, as I told you some comments above...

**Comment by lelive** [comment]
ok, thank you
