### ISSUE TITLE
No bean named 'ocr-extract' is defined

### ISSUE THREAD

**Issue by DavBE** [keensoft/alfresco-simple-ocr#44]
## BUG
Can't use OCR 

### Expected behavior
Use OCR

### Actual behavior
Message "Some error happened when processing your request, OCR has not been applied to the document" when clicking the OCR button.

### Steps to reproduce the behavior
Open a scanned PDF and click on the OCR button

### Additional details (analysis so far, log statements, references, etc.)
```
2017-11-30 13:34:43,548 ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-2] Exception from executeScript: 10300006 Wrapped Exception (with status template): No bean named 'ocr-extract' is defined
org.springframework.extensions.webscripts.WebScriptException: 10300006 Wrapped Exception (with status template): No bean named 'ocr-extract' is defined
        at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1138)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
        at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:519)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2486)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'ocr-extract' is defined
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:575)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1111)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:276)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1123)
        at org.alfresco.repo.action.ActionServiceImpl.getActionDefinition(ActionServiceImpl.java:286)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.alfresco.repo.security.permissions.impl.AlwaysProceedMethodInterceptor.invoke(AlwaysProceedMethodInterceptor.java:41)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:166)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy47.getActionDefinition(Unknown Source)
        at org.alfresco.repo.web.scripts.rule.AbstractRuleWebScript.parseJsonParameterValues(AbstractRuleWebScript.java:343)
        at org.alfresco.repo.web.scripts.rule.AbstractRuleWebScript.parseJsonAction(AbstractRuleWebScript.java:255)
        at org.alfresco.repo.web.scripts.rule.ActionQueuePost.executeImpl(ActionQueuePost.java:75)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
        ... 36 more
```

### Tell us about your environment
Ubuntu 16.04 x64

Hello,

I have installed alfresco-simple-ocr by placing simple-ocr-repo-2.3.1.jar and simple-ocr-share-2.3.1.jar in /opt/alfresco-community/modules/share.

Also, I have edited alfresco-global.properties and added the following lines : 

```
ocr.command=/usr/bin/pdfsandwich
ocr.output.verbose=true
ocr.output.file.prefix.command=-o

ocr.extra.commands=-verbose -lang spa+eng+fra
ocr.server.os=linux
```

Could you please help ?

Regards,

David

**Comment by angelborroy-ks** [comment]
Repo modules must be installed in /opt/alfresco-community/modules/platform

**Comment by DavBE** [comment]
Hi angelborroy-ks,

Thanks for your quick reply!

I moved simple-ocr-repo-2.3.1.jar to /opt/alfresco-community/modules/platform/ :

```
root:/opt/alfresco-community/modules# ll -R
.:
total 16
drwxr-xr-x  4 root root 4096 Nov 30 13:58 ./
drwxr-xr-x 14 root root 4096 Nov 30 13:31 ../
drwxr-xr-x  2 root root 4096 Nov 30 13:58 platform/
drwxr-xr-x  2 root root 4096 Nov 30 13:58 share/

./platform:
total 36
drwxr-xr-x 2 root root  4096 Nov 30 13:58 ./
drwxr-xr-x 4 root root  4096 Nov 30 13:58 ../
-rw-rw-r-- 1 root root 27776 Nov 30 11:46 simple-ocr-repo-2.3.1.jar

./share:
total 20
drwxr-xr-x 2 root root  4096 Nov 30 13:58 ./
drwxr-xr-x 4 root root  4096 Nov 30 13:58 ../
-rw-rw-r-- 1 root root 12213 Nov 30 11:46 simple-ocr-share-2.3.1.jar
```

but the issue is not resolved. Any clue ?

Regards,

David

**Comment by angelborroy-ks** [comment]
Please, re-start Alfresco.

**Comment by DavBE** [comment]
Done of course

**Comment by angelborroy-ks** [comment]
Alfresco release?
Have you following line at Tomcat's alfresco.xml file?

  <Loader className="org.apache.catalina.loader.VirtualWebappLoader" virtualClasspath="${catalina.base}/modules/platform/*.jar" />

**Comment by DavBE** [comment]
5.2.0 (re21f2be5-b22)

What do you mean following line ?

**Comment by angelborroy-ks** [comment]
I edited the comment (as the line was missed), please read it again.

**Comment by DavBE** [comment]
I couldn't find any alfresco.xml file : 
```
root:/opt/alfresco-community# find . -name alfresco.xml
root:/opt/alfresco-community# grep -ri VirtualWebappLoader .
./tomcat/conf/Catalina/localhost/share.xml:  <Loader className="org.apache.catalina.loader.VirtualWebappLoader" virtualClasspath="${catalina.base}/../modules/share/*.jar" />
Binary file ./tomcat/lib/catalina.jar matches
```

I should mention that the platform directory didn't exist in /opt/alfresco-community/modules, so I created it. There only was a "share" directory.

**Comment by angelborroy-ks** [comment]
Ok, create the file `./tomcat/conf/Catalina/localhost/alfresco.xml` with the following content

```xml
<?xml version='1.0' encoding='utf-8'?>
<Context crossContext="true">
  <Loader className="org.apache.catalina.loader.VirtualWebappLoader" virtualClasspath="${catalina.base}/modules/platform/*.jar" /> 
</Context>

```

And re-start Alfresco.

**Comment by DavBE** [comment]
```
Your OCR request has been successfully processed, new version for the document will be available in minutes
```

Thank you @angelborroy-ks

**Comment by amar7295** [comment]
hi @angelborroy-ks 

I have tried your suggestion but after making changes in the alfresco xml I am not able to log in to the alfresco.

It shows "Your authentication details haven't been recognized or Alfresco Content Services may not be available at this time." error.

how can I solve this?

thanks and regards.
